# Generated by Django 4.1.10 on 2024-08-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_types', '0007_delete_relationtypeold'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='spantype',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
